apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: contract-intelligence-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 60
      containers:
        - image: gcr.io/${PROJECT_ID}/contract-intelligence-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://contract-intelligence-backend-${REGION}-${PROJECT_ID}.a.run.app"
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
